# playbooks/ec2_shutdown.yaml

---
- hosts: all
  become: true

  tasks:
    - name: Shutdown Ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -h now
      when:
        ansible_facts['os_family'] == "Debian"
